databases:
  - name: edusync-db
    databaseName: edusync
    user: edusync
    plan: free

services:
  - type: web
    name: edusync
    runtime: python
    plan: free
    rootDir: EduSync
    buildCommand: "chmod +x build.sh && ./build.sh"
    startCommand: "gunicorn EduSync.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: edusync-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DEBUG
        value: "False"
      - key: RENDER
        value: "True"
      - key: DJANGO_SUPERUSER_USERNAME
        value: "admin"
      - key: DJANGO_SUPERUSER_EMAIL
        value: "admin@edusync.com"
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: FORCE_LOAD_FIXTURES
        value: "true"
